name = "Firmament Ages"
author = "PhoenixFlyy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afe377e4d4a24a965dfb38a97916add5ec99cc8bf9d352b923f66418d606cea0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
