name = "Firmament Ages"
author = "PhoenixFlyy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fda48883ef19dcf8244188a97e4689be7a8f1eccd2fe0116833fcf471cec11b6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
