name = "Firmament Ages"
author = "PhoenixFlyy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02d4fc65cf11eceadb8382ea6f8c8f5ff22b43b91420289fc207b191c6d5ecbd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
