// priority: 1000
// Firmament Ages - shared constants.
// Startup scripts run first on client and server; `global` is shared with server_scripts and
// client_scripts, so every other script reads its stage names from here.
// All player-facing strings are English.

global.FA = {
  NS: 'firmages',

  // Age stages, cumulative, in order. Stage ids must match config/progressivestages/stages/*.toml.
  AGES: ['dawn', 'age_0', 'age_1', 'age_2', 'age_3', 'age_4', 'age_5', 'age_6', 'age_7', 'age_8', 'age_9'],

  AGE_TITLES: {
    dawn: 'Dawn',
    age_0: 'Age 0: Stone Age',
    age_1: 'Age 1: Bronze Age',
    age_2: 'Age 2: Iron Age',
    age_3: 'Age 3: Arcane Age',
    age_4: 'Age 4: Industrial Age',
    age_5: 'Age 5: Electric Age',
    age_6: 'Age 6: Information Age',
    age_7: 'Age 7: Space Age',
    age_8: 'Age 8: Quantum Age',
    age_9: 'Age 9: Singularity Age',
    finale_won: 'Beyond the Firmament'
  },

  AGE_SUBTITLES: {
    age_0: 'Fire is tamed. Clay and copper await.',
    age_1: 'The first alloys. New veins can be found.',
    age_2: 'The map opens. Iron veins become visible.',
    age_3: 'Spirits stir. The Nether opens.',
    age_4: 'Coke, steel and the first current.',
    age_5: 'The grid hums.',
    age_6: 'Data flows. The End opens.',
    age_7: 'The sky is no longer the limit.',
    age_8: 'Matter bends.',
    age_9: 'The Stargate waits.',
    finale_won: 'Trophies unlocked.'
  },

  // Mob ladder: which mob_N belongs to which age stage (Doc 08 section 2.3 / section 5).
  MOB_STAGE_FOR: {
    dawn: 'mob_0', age_0: 'mob_0', age_1: 'mob_1', age_2: 'mob_2', age_3: 'mob_3', age_4: 'mob_4',
    age_5: 'mob_5', age_6: 'mob_6', age_7: 'mob_7', age_8: 'mob_8', age_9: 'mob_9'
  },

  // true: mob_0..mob_N are all kept (see mob_1.toml header for why). false: Doc 08 swap (revoke mob_(N-1)).
  MOB_LADDER_CUMULATIVE: true,

  // Helper stages with a window [grantedWith, revokedWith). null = never revoked.
  // Doc 08 section 2.3 and Doc 10 v3 section 6.2.
  HELPER_WINDOWS: {
    ftbchunks_mapping: ['age_2', null],
    tool_toms_storage: ['age_2', 'age_6'],
    tool_ie_alloy_kiln: ['age_4', 'age_5'],
    tool_ie_capacitor: ['age_4', 'age_6'],
    tool_mech_spawner: ['age_4', 'age_6']
  },

  // FTB Chunks quota granted with the Industrial Age (decision r8 A).
  CHUNK_QUOTA: { stage: 'age_4', claims: 25, forceLoads: 25 },

  // Items that never appear in the pack (Doc 10 v3 section 7.2, all Ages).
  // Used by server_scripts/tags/hidden_from_viewers.js (tag c:hidden_from_recipe_viewers) and by
  // client_scripts/viewer_static.js (KubeJS RecipeViewerEvents). The PS stage "disabled" locks them too.
  HIDDEN_ITEMS: [
    'create:zinc_ore', 'create:deepslate_zinc_ore', 'create:raw_zinc', 'create:raw_zinc_block',
    'create:zinc_ingot', 'create:zinc_block', 'create:brass_ingot',
    'create:iron_sheet', 'create:copper_sheet', 'create:golden_sheet', 'create:brass_sheet',
    'create:crushed_raw_iron', 'create:crushed_raw_gold', 'create:crushed_raw_copper', 'create:crushed_raw_zinc',
    'create:crushed_raw_osmium', 'create:crushed_raw_platinum', 'create:crushed_raw_silver', 'create:crushed_raw_tin',
    'create:crushed_raw_lead', 'create:crushed_raw_quicksilver', 'create:crushed_raw_aluminum',
    'create:crushed_raw_uranium', 'create:crushed_raw_nickel',
    'occultism:silver_ore', 'occultism:silver_ore_deepslate', 'occultism:raw_silver', 'occultism:raw_silver_block',
    'occultism:silver_ingot', 'occultism:silver_block', 'occultism:silver_nugget', 'occultism:silver_dust',
    'ftbquests:book',
    // Arcane and Industrial Age (Doc 10 v3 sections 1.2, 1.6, 7.2); same list as stages/disabled.toml.
    'occultism:book_of_calling_foliot_transport_items', 'ars_additions:warp_index',
    'ars_additions:stabilized_warp_index', 'immersiveengineering:pickaxe_steel', 'immersiveengineering:shovel_steel',
    'immersiveengineering:axe_steel', 'immersiveengineering:hoe_steel', 'immersiveengineering:sword_steel',
    'immersiveengineering:armor_steel_helmet', 'immersiveengineering:armor_steel_chestplate',
    'immersiveengineering:armor_steel_leggings', 'immersiveengineering:armor_steel_boots',
    'immersiveengineering:windmill', 'immersiveengineering:windmill_blade', 'immersiveengineering:windmill_sail',
    'immersiveengineering:watermill', 'immersiveengineering:waterwheel_segment', 'immersiveengineering:dynamo',
    'immersiveengineering:thermoelectric_generator', 'immersiveengineering:refinery',
    'immersiveengineering:conveyor_dropper', 'immersiveengineering:conveyor_extract',
    'immersiveengineering:conveyor_redstone', 'immersiveengineering:conveyor_splitter',
    'immersiveengineering:conveyor_vertical', 'immersiveengineering:ingot_silver',
    'immersiveengineering:ingot_nickel', 'immersiveengineering:ingot_steel', 'immersiveengineering:nugget_copper',
    'immersiveengineering:plate_copper', 'immersiveengineering:plate_iron', 'immersiveengineering:plate_gold',
    'immersiveengineering:plate_silver', 'immersiveengineering:plate_nickel', 'immersiveengineering:plate_steel',
    'immersiveengineering:ore_silver', 'immersiveengineering:ore_nickel',
    'immersiveengineering:deepslate_ore_silver', 'immersiveengineering:deepslate_ore_nickel',
    'immersiveengineering:raw_silver', 'immersiveengineering:raw_nickel', 'immersiveengineering:raw_block_silver',
    'immersiveengineering:raw_block_nickel', 'createaddition:barbed_wire', 'createaddition:bioethanol_bucket',
    'createaddition:biomass', 'createaddition:biomass_pellet', 'createaddition:biomass_pellet_block',
    'createaddition:brass_rod', 'createaddition:cake_base', 'createaddition:cake_base_baked',
    'createaddition:capacitor', 'createaddition:chocolate_cake', 'createaddition:connector',
    'createaddition:copper_rod', 'createaddition:copper_spool', 'createaddition:copper_wire',
    'createaddition:creative_energy', 'createaddition:diamond_grit', 'createaddition:diamond_grit_sandpaper',
    'createaddition:digital_adapter', 'createaddition:electric_pump', 'createaddition:electrum_amulet',
    'createaddition:electrum_block', 'createaddition:electrum_ingot', 'createaddition:electrum_nugget',
    'createaddition:electrum_rod', 'createaddition:electrum_sheet', 'createaddition:electrum_spool',
    'createaddition:electrum_wire', 'createaddition:festive_spool', 'createaddition:gold_rod',
    'createaddition:gold_spool', 'createaddition:gold_wire', 'createaddition:honey_cake', 'createaddition:iron_rod',
    'createaddition:iron_wire', 'createaddition:large_connector', 'createaddition:modular_accumulator',
    'createaddition:portable_energy_interface', 'createaddition:redstone_relay', 'createaddition:rolling_mill',
    'createaddition:seed_oil_bucket', 'createaddition:servo_motor', 'createaddition:small_light_connector',
    'createaddition:spool', 'createaddition:straw', 'createaddition:tesla_coil', 'createaddition:zinc_sheet',
    // Electric to Singularity Age (Doc 10 v3 section 7.2); same list as stages/disabled.toml, generated from the registry.
    // Immersive Petroleum: the gas generator (the IE Diesel Generator is the one FE generator of the Electric Age)
    'immersivepetroleum:gas_generator',
    // Create: Diesel Generators: everything except the engines and their upgrades (Doc 10 v3 section 7.2)
    'createdieselgenerators:andesite_girder', 'createdieselgenerators:andesite_girder_strut',
    'createdieselgenerators:asphalt_block', 'createdieselgenerators:asphalt_slab',
    'createdieselgenerators:asphalt_stairs', 'createdieselgenerators:basin_lid',
    'createdieselgenerators:biodiesel_bucket', 'createdieselgenerators:black_cement_bucket',
    'createdieselgenerators:blue_cement_bucket', 'createdieselgenerators:brown_cement_bucket',
    'createdieselgenerators:bulk_fermenter', 'createdieselgenerators:burner', 'createdieselgenerators:canister',
    'createdieselgenerators:chemical_sprayer', 'createdieselgenerators:chemical_sprayer_lighter',
    'createdieselgenerators:chemical_turret', 'createdieselgenerators:chip_wood_beam',
    'createdieselgenerators:chip_wood_block', 'createdieselgenerators:chip_wood_slab',
    'createdieselgenerators:chip_wood_stairs', 'createdieselgenerators:crude_oil_bucket',
    'createdieselgenerators:cyan_cement_bucket', 'createdieselgenerators:diesel_bucket',
    'createdieselgenerators:distillation_controller', 'createdieselgenerators:entity_filter',
    'createdieselgenerators:ethanol_bucket', 'createdieselgenerators:gasoline_bucket',
    'createdieselgenerators:gray_cement_bucket', 'createdieselgenerators:green_cement_bucket',
    'createdieselgenerators:hammer', 'createdieselgenerators:kelp_handle',
    'createdieselgenerators:light_blue_cement_bucket', 'createdieselgenerators:light_gray_cement_bucket',
    'createdieselgenerators:lighter', 'createdieselgenerators:lime_cement_bucket',
    'createdieselgenerators:magenta_cement_bucket', 'createdieselgenerators:mold',
    'createdieselgenerators:oil_barrel', 'createdieselgenerators:oil_scanner',
    'createdieselgenerators:orange_cement_bucket', 'createdieselgenerators:pink_cement_bucket',
    'createdieselgenerators:plant_oil_bucket', 'createdieselgenerators:pumpjack_bearing',
    'createdieselgenerators:pumpjack_crank', 'createdieselgenerators:pumpjack_head',
    'createdieselgenerators:pumpjack_hole', 'createdieselgenerators:purple_cement_bucket',
    'createdieselgenerators:red_cement_bucket', 'createdieselgenerators:sheet_metal_panel',
    'createdieselgenerators:track_layers_bag', 'createdieselgenerators:white_cement_bucket',
    'createdieselgenerators:wire_cutters', 'createdieselgenerators:wood_chip',
    'createdieselgenerators:yellow_cement_bucket',
    // Mekanism (Doc 10 v3 section 7.2): QIO, Dimensional Stabilizer, Anchor Upgrade, Formulaic Assemblicator, Precision Sawmill and the sawing factories, Mekanism tin/lead/uranium/steel/bronze ingots and nuggets, every Mekanism ore block, raw ore and raw-ore block
    'mekanism:advanced_sawing_factory', 'mekanism:basic_sawing_factory', 'mekanism:block_raw_lead',
    'mekanism:block_raw_osmium', 'mekanism:block_raw_tin', 'mekanism:block_raw_uranium',
    'mekanism:deepslate_fluorite_ore', 'mekanism:deepslate_lead_ore', 'mekanism:deepslate_osmium_ore',
    'mekanism:deepslate_silver_ore', 'mekanism:deepslate_tin_ore', 'mekanism:deepslate_uranium_ore',
    'mekanism:dimensional_stabilizer', 'mekanism:elite_sawing_factory', 'mekanism:fluorite_ore',
    'mekanism:formulaic_assemblicator', 'mekanism:ingot_bronze', 'mekanism:ingot_lead', 'mekanism:ingot_steel',
    'mekanism:ingot_tin', 'mekanism:ingot_uranium', 'mekanism:lead_ore', 'mekanism:nugget_bronze',
    'mekanism:nugget_lead', 'mekanism:nugget_steel', 'mekanism:nugget_tin', 'mekanism:nugget_uranium',
    'mekanism:osmium_ore', 'mekanism:portable_qio_dashboard', 'mekanism:precision_sawmill', 'mekanism:qio_dashboard',
    'mekanism:qio_drive_array', 'mekanism:qio_drive_base', 'mekanism:qio_drive_hyper_dense',
    'mekanism:qio_drive_supermassive', 'mekanism:qio_drive_time_dilating', 'mekanism:qio_exporter',
    'mekanism:qio_importer', 'mekanism:qio_redstone_adapter', 'mekanism:raw_lead', 'mekanism:raw_osmium',
    'mekanism:raw_tin', 'mekanism:raw_uranium', 'mekanism:silver_ore', 'mekanism:tin_ore',
    'mekanism:ultimate_sawing_factory', 'mekanism:upgrade_anchor', 'mekanism:uranium_ore',
    // Mekanism Generators: heat, solar, advanced solar, wind and bio generators and the solar and geothermal MekaSuit modules (no passive or cheap power)
    'mekanismgenerators:advanced_solar_generator', 'mekanismgenerators:bio_generator',
    'mekanismgenerators:heat_generator', 'mekanismgenerators:module_geothermal_generator_unit',
    'mekanismgenerators:module_solar_recharging_unit', 'mekanismgenerators:solar_generator',
    'mekanismgenerators:wind_generator',
    // Mekanism Tools: the bronze, steel, osmium and lapis sets and every paxel (refined obsidian and glowstone stay)
    'mekanismtools:bronze_axe', 'mekanismtools:bronze_boots', 'mekanismtools:bronze_chestplate',
    'mekanismtools:bronze_helmet', 'mekanismtools:bronze_hoe', 'mekanismtools:bronze_leggings',
    'mekanismtools:bronze_paxel', 'mekanismtools:bronze_pickaxe', 'mekanismtools:bronze_shield',
    'mekanismtools:bronze_shovel', 'mekanismtools:bronze_sword', 'mekanismtools:diamond_paxel',
    'mekanismtools:gold_paxel', 'mekanismtools:iron_paxel', 'mekanismtools:lapis_lazuli_axe',
    'mekanismtools:lapis_lazuli_boots', 'mekanismtools:lapis_lazuli_chestplate', 'mekanismtools:lapis_lazuli_helmet',
    'mekanismtools:lapis_lazuli_hoe', 'mekanismtools:lapis_lazuli_leggings', 'mekanismtools:lapis_lazuli_paxel',
    'mekanismtools:lapis_lazuli_pickaxe', 'mekanismtools:lapis_lazuli_shield', 'mekanismtools:lapis_lazuli_shovel',
    'mekanismtools:lapis_lazuli_sword', 'mekanismtools:netherite_paxel', 'mekanismtools:osmium_axe',
    'mekanismtools:osmium_boots', 'mekanismtools:osmium_chestplate', 'mekanismtools:osmium_helmet',
    'mekanismtools:osmium_hoe', 'mekanismtools:osmium_leggings', 'mekanismtools:osmium_paxel',
    'mekanismtools:osmium_pickaxe', 'mekanismtools:osmium_shield', 'mekanismtools:osmium_shovel',
    'mekanismtools:osmium_sword', 'mekanismtools:refined_glowstone_paxel', 'mekanismtools:refined_obsidian_paxel',
    'mekanismtools:steel_axe', 'mekanismtools:steel_boots', 'mekanismtools:steel_chestplate',
    'mekanismtools:steel_helmet', 'mekanismtools:steel_hoe', 'mekanismtools:steel_leggings',
    'mekanismtools:steel_paxel', 'mekanismtools:steel_pickaxe', 'mekanismtools:steel_shield',
    'mekanismtools:steel_shovel', 'mekanismtools:steel_sword', 'mekanismtools:stone_paxel',
    'mekanismtools:wood_paxel',
    // Mekanism Additions: obsidian TNT
    'mekanismadditions:obsidian_tnt',
    // Mekanism: More Machine: replicators and UU matter, recycler, planting station, their factories, the duplicate silver family, the stamper, lathe, rolling mill and presser (second plate, rod, wire and processor stations), creative factories and the passive large heat/wind and solar heat generators
    'mekmm:advanced_lathing_factory', 'mekmm:advanced_planting_factory', 'mekmm:advanced_pressing_factory',
    'mekmm:advanced_recycling_factory', 'mekmm:advanced_replicating_factory', 'mekmm:advanced_rolling_mill_factory',
    'mekmm:advanced_stamping_factory', 'mekmm:basic_lathing_factory', 'mekmm:basic_planting_factory',
    'mekmm:basic_pressing_factory', 'mekmm:basic_recycling_factory', 'mekmm:basic_replicating_factory',
    'mekmm:basic_rolling_mill_factory', 'mekmm:basic_stamping_factory', 'mekmm:block_raw_silver',
    'mekmm:block_silver', 'mekmm:chemical_replicator', 'mekmm:clump_silver', 'mekmm:cnc_lathe',
    'mekmm:cnc_rolling_mill', 'mekmm:cnc_stamper', 'mekmm:creative_centrifuging_factory',
    'mekmm:creative_crystallizing_factory', 'mekmm:creative_dissolving_factory', 'mekmm:creative_lathing_factory',
    'mekmm:creative_liquifying_factory', 'mekmm:creative_oxidizing_factory', 'mekmm:creative_painting_factory',
    'mekmm:creative_pigment_extracting_factory', 'mekmm:creative_planting_factory', 'mekmm:creative_pressing_factory',
    'mekmm:creative_pressurised_reacting_factory', 'mekmm:creative_recycling_factory',
    'mekmm:creative_replicating_factory', 'mekmm:creative_rolling_mill_factory', 'mekmm:creative_stamping_factory',
    'mekmm:creative_washing_factory', 'mekmm:crystal_silver', 'mekmm:deepslate_silver_ore',
    'mekmm:dense_lathing_factory', 'mekmm:dense_planting_factory', 'mekmm:dense_pressing_factory',
    'mekmm:dense_recycling_factory', 'mekmm:dense_replicating_factory', 'mekmm:dense_rolling_mill_factory',
    'mekmm:dense_stamping_factory', 'mekmm:dirty_dust_silver', 'mekmm:dust_silver', 'mekmm:elite_lathing_factory',
    'mekmm:elite_planting_factory', 'mekmm:elite_pressing_factory', 'mekmm:elite_recycling_factory',
    'mekmm:elite_replicating_factory', 'mekmm:elite_rolling_mill_factory', 'mekmm:elite_stamping_factory',
    'mekmm:enriched_silver', 'mekmm:fluid_replicator', 'mekmm:ingot_silver', 'mekmm:large_heat_generator',
    'mekmm:large_wind_generator', 'mekmm:multiversal_lathing_factory', 'mekmm:multiversal_planting_factory',
    'mekmm:multiversal_pressing_factory', 'mekmm:multiversal_recycling_factory',
    'mekmm:multiversal_replicating_factory', 'mekmm:multiversal_rolling_mill_factory',
    'mekmm:multiversal_stamping_factory', 'mekmm:nugget_silver', 'mekmm:overclocked_lathing_factory',
    'mekmm:overclocked_planting_factory', 'mekmm:overclocked_pressing_factory', 'mekmm:overclocked_recycling_factory',
    'mekmm:overclocked_replicating_factory', 'mekmm:overclocked_rolling_mill_factory',
    'mekmm:overclocked_stamping_factory', 'mekmm:planting_station', 'mekmm:presser', 'mekmm:quantum_lathing_factory',
    'mekmm:quantum_planting_factory', 'mekmm:quantum_pressing_factory', 'mekmm:quantum_recycling_factory',
    'mekmm:quantum_replicating_factory', 'mekmm:quantum_rolling_mill_factory', 'mekmm:quantum_stamping_factory',
    'mekmm:raw_silver', 'mekmm:recycler', 'mekmm:replicator', 'mekmm:scrap', 'mekmm:scrap_box', 'mekmm:shard_silver',
    'mekmm:silver_ore', 'mekmm:solar_heat_generator', 'mekmm:ultimate_lathing_factory',
    'mekmm:ultimate_planting_factory', 'mekmm:ultimate_pressing_factory', 'mekmm:ultimate_recycling_factory',
    'mekmm:ultimate_replicating_factory', 'mekmm:ultimate_rolling_mill_factory', 'mekmm:ultimate_stamping_factory',
    'mekmm:uu_matter',
    // Evolved Mekanism: the creative tier, the paxels, the sawing factories, the solar generators, the solidification chamber and its molds (no molten-metal economy next to the TFC fluids), its QIO drive
    'evolvedmekanism:advanced_solar_generator', 'evolvedmekanism:better_gold_paxel',
    'evolvedmekanism:creative_alloying_factory', 'evolvedmekanism:creative_combining_factory',
    'evolvedmekanism:creative_compressing_factory', 'evolvedmekanism:creative_control_circuit',
    'evolvedmekanism:creative_crushing_factory', 'evolvedmekanism:creative_enriching_factory',
    'evolvedmekanism:creative_induction_cell', 'evolvedmekanism:creative_induction_provider',
    'evolvedmekanism:creative_infusing_factory', 'evolvedmekanism:creative_injecting_factory',
    'evolvedmekanism:creative_logistical_transporter', 'evolvedmekanism:creative_mechanical_pipe',
    'evolvedmekanism:creative_personal_barrel', 'evolvedmekanism:creative_personal_chest',
    'evolvedmekanism:creative_pressurized_tube', 'evolvedmekanism:creative_purifying_factory',
    'evolvedmekanism:creative_sawing_factory', 'evolvedmekanism:creative_smelting_factory',
    'evolvedmekanism:creative_solar_generator', 'evolvedmekanism:creative_thermodynamic_conductor',
    'evolvedmekanism:creative_tier_installer', 'evolvedmekanism:creative_universal_cable',
    'evolvedmekanism:dense_sawing_factory', 'evolvedmekanism:dense_solar_generator',
    'evolvedmekanism:elite_solar_generator', 'evolvedmekanism:mold_coin', 'evolvedmekanism:mold_dust',
    'evolvedmekanism:mold_gear', 'evolvedmekanism:mold_gem', 'evolvedmekanism:mold_ingot',
    'evolvedmekanism:mold_nugget', 'evolvedmekanism:mold_plate', 'evolvedmekanism:mold_rod',
    'evolvedmekanism:mold_storage_block', 'evolvedmekanism:mold_wire', 'evolvedmekanism:multiversal_sawing_factory',
    'evolvedmekanism:multiversal_solar_generator', 'evolvedmekanism:overclocked_sawing_factory',
    'evolvedmekanism:overclocked_solar_generator', 'evolvedmekanism:plaslitherite_paxel',
    'evolvedmekanism:qio_drive_black_hole', 'evolvedmekanism:qio_drive_boosted', 'evolvedmekanism:qio_drive_creative',
    'evolvedmekanism:qio_drive_hypra_solidified', 'evolvedmekanism:qio_drive_singularity',
    'evolvedmekanism:quantum_sawing_factory', 'evolvedmekanism:quantum_solar_generator',
    'evolvedmekanism:refined_redstone_paxel', 'evolvedmekanism:solidification_chamber',
    'evolvedmekanism:ultimate_solar_generator',
    // AE2: Vibration Chamber
    'ae2:vibration_chamber',
    // AdvancedAE: Quantum Armor
    'advanced_ae:quantum_boots', 'advanced_ae:quantum_chestplate', 'advanced_ae:quantum_helmet',
    'advanced_ae:quantum_leggings',
    // Draconic Evolution: Energy Core and its stabilizer and pylon, the crystal network, generator, mob grinder, stabilized spawner, draconium chest, disenchanter, the dislocator portal blocks, the energy-link modules of the crystal network (the flux gate and the reactor stay)
    'draconicevolution:basic_io_crystal', 'draconicevolution:basic_relay_crystal',
    'draconicevolution:basic_wireless_crystal', 'draconicevolution:crystal_binder', 'draconicevolution:disenchanter',
    'draconicevolution:dislocator_pedestal', 'draconicevolution:dislocator_receptacle',
    'draconicevolution:draconic_io_crystal', 'draconicevolution:draconic_relay_crystal',
    'draconicevolution:draconic_wireless_crystal', 'draconicevolution:draconium_chest',
    'draconicevolution:energy_core', 'draconicevolution:energy_core_stabilizer', 'draconicevolution:energy_pylon',
    'draconicevolution:generator', 'draconicevolution:grinder', 'draconicevolution:item_chaotic_energy_link',
    'draconicevolution:item_draconic_energy_link', 'draconicevolution:item_wyvern_energy_link',
    'draconicevolution:stabilized_spawner', 'draconicevolution:wyvern_io_crystal',
    'draconicevolution:wyvern_relay_crystal', 'draconicevolution:wyvern_wireless_crystal',
    // Ad Astra: Compressor, Etrionic Blast Furnace, Energizer, Coal Generator, Solar Panel, Fuel Refinery, its iron and steel plates, rods and steel
    'ad_astra:coal_generator', 'ad_astra:compressor', 'ad_astra:energizer', 'ad_astra:etrionic_blast_furnace',
    'ad_astra:fuel_refinery', 'ad_astra:iron_plate', 'ad_astra:iron_rod', 'ad_astra:solar_panel',
    'ad_astra:steel_ingot', 'ad_astra:steel_nugget', 'ad_astra:steel_plate', 'ad_astra:steel_rod',
    // Stargate Journey: the naquadah generator
    'sgjourney:naquadah_generator_core', 'sgjourney:naquadah_generator_mark_i',
    'sgjourney:naquadah_generator_mark_ii',
    // Mystical Agriculture and Agradditions: every tool, weapon, armour piece, paxel and augment (Doc 08 section 4.4)
    'mysticalagradditions:awakened_supremium_paxel', 'mysticalagradditions:imperium_paxel',
    'mysticalagradditions:inferium_paxel', 'mysticalagradditions:prudentium_paxel',
    'mysticalagradditions:supremium_paxel', 'mysticalagradditions:tertium_paxel',
    'mysticalagriculture:absorption_i_augment', 'mysticalagriculture:absorption_ii_augment',
    'mysticalagriculture:absorption_iii_augment', 'mysticalagriculture:absorption_iv_augment',
    'mysticalagriculture:absorption_v_augment', 'mysticalagriculture:attack_aoe_i_augment',
    'mysticalagriculture:attack_aoe_ii_augment', 'mysticalagriculture:attack_aoe_iii_augment',
    'mysticalagriculture:awakened_supremium_axe', 'mysticalagriculture:awakened_supremium_boots',
    'mysticalagriculture:awakened_supremium_bow', 'mysticalagriculture:awakened_supremium_chestplate',
    'mysticalagriculture:awakened_supremium_crossbow', 'mysticalagriculture:awakened_supremium_fishing_rod',
    'mysticalagriculture:awakened_supremium_helmet', 'mysticalagriculture:awakened_supremium_hoe',
    'mysticalagriculture:awakened_supremium_leggings', 'mysticalagriculture:awakened_supremium_pickaxe',
    'mysticalagriculture:awakened_supremium_scythe', 'mysticalagriculture:awakened_supremium_shears',
    'mysticalagriculture:awakened_supremium_shovel', 'mysticalagriculture:awakened_supremium_sickle',
    'mysticalagriculture:awakened_supremium_sword', 'mysticalagriculture:blindness_resistance_augment',
    'mysticalagriculture:diamond_scythe', 'mysticalagriculture:diamond_sickle',
    'mysticalagriculture:fire_resistance_augment', 'mysticalagriculture:flight_augment',
    'mysticalagriculture:haste_i_augment', 'mysticalagriculture:haste_ii_augment',
    'mysticalagriculture:haste_iii_augment', 'mysticalagriculture:health_boost_i_augment',
    'mysticalagriculture:health_boost_ii_augment', 'mysticalagriculture:health_boost_iii_augment',
    'mysticalagriculture:health_boost_iv_augment', 'mysticalagriculture:health_boost_v_augment',
    'mysticalagriculture:hunger_resistance_augment', 'mysticalagriculture:imperium_axe',
    'mysticalagriculture:imperium_boots', 'mysticalagriculture:imperium_bow',
    'mysticalagriculture:imperium_chestplate', 'mysticalagriculture:imperium_crossbow',
    'mysticalagriculture:imperium_fishing_rod', 'mysticalagriculture:imperium_helmet',
    'mysticalagriculture:imperium_hoe', 'mysticalagriculture:imperium_leggings',
    'mysticalagriculture:imperium_pickaxe', 'mysticalagriculture:imperium_scythe',
    'mysticalagriculture:imperium_shears', 'mysticalagriculture:imperium_shovel',
    'mysticalagriculture:imperium_sickle', 'mysticalagriculture:imperium_sword', 'mysticalagriculture:inferium_axe',
    'mysticalagriculture:inferium_boots', 'mysticalagriculture:inferium_bow',
    'mysticalagriculture:inferium_chestplate', 'mysticalagriculture:inferium_crossbow',
    'mysticalagriculture:inferium_fishing_rod', 'mysticalagriculture:inferium_helmet',
    'mysticalagriculture:inferium_hoe', 'mysticalagriculture:inferium_leggings',
    'mysticalagriculture:inferium_pickaxe', 'mysticalagriculture:inferium_scythe',
    'mysticalagriculture:inferium_shears', 'mysticalagriculture:inferium_shovel',
    'mysticalagriculture:inferium_sickle', 'mysticalagriculture:inferium_sword',
    'mysticalagriculture:jump_boost_i_augment', 'mysticalagriculture:jump_boost_ii_augment',
    'mysticalagriculture:jump_boost_iii_augment', 'mysticalagriculture:luck_i_augment',
    'mysticalagriculture:luck_ii_augment', 'mysticalagriculture:luck_iii_augment',
    'mysticalagriculture:mining_aoe_i_augment', 'mysticalagriculture:mining_aoe_ii_augment',
    'mysticalagriculture:mining_aoe_iii_augment', 'mysticalagriculture:mining_aoe_iv_augment',
    'mysticalagriculture:mining_fatigue_resistance_augment', 'mysticalagriculture:nausea_resistance_augment',
    'mysticalagriculture:night_vision_augment', 'mysticalagriculture:no_fall_damage_augment',
    'mysticalagriculture:pathing_aoe_i_augment', 'mysticalagriculture:pathing_aoe_ii_augment',
    'mysticalagriculture:pathing_aoe_iii_augment', 'mysticalagriculture:pathing_aoe_iv_augment',
    'mysticalagriculture:poison_resistance_augment', 'mysticalagriculture:prudentium_axe',
    'mysticalagriculture:prudentium_boots', 'mysticalagriculture:prudentium_bow',
    'mysticalagriculture:prudentium_chestplate', 'mysticalagriculture:prudentium_crossbow',
    'mysticalagriculture:prudentium_fishing_rod', 'mysticalagriculture:prudentium_helmet',
    'mysticalagriculture:prudentium_hoe', 'mysticalagriculture:prudentium_leggings',
    'mysticalagriculture:prudentium_pickaxe', 'mysticalagriculture:prudentium_scythe',
    'mysticalagriculture:prudentium_shears', 'mysticalagriculture:prudentium_shovel',
    'mysticalagriculture:prudentium_sickle', 'mysticalagriculture:prudentium_sword',
    'mysticalagriculture:slow_falling_augment', 'mysticalagriculture:slowness_resistance_augment',
    'mysticalagriculture:speed_i_augment', 'mysticalagriculture:speed_ii_augment',
    'mysticalagriculture:speed_iii_augment', 'mysticalagriculture:step_assist_augment',
    'mysticalagriculture:strength_i_augment', 'mysticalagriculture:strength_ii_augment',
    'mysticalagriculture:strength_iii_augment', 'mysticalagriculture:supremium_axe',
    'mysticalagriculture:supremium_boots', 'mysticalagriculture:supremium_bow',
    'mysticalagriculture:supremium_chestplate', 'mysticalagriculture:supremium_crossbow',
    'mysticalagriculture:supremium_fishing_rod', 'mysticalagriculture:supremium_helmet',
    'mysticalagriculture:supremium_hoe', 'mysticalagriculture:supremium_leggings',
    'mysticalagriculture:supremium_pickaxe', 'mysticalagriculture:supremium_scythe',
    'mysticalagriculture:supremium_shears', 'mysticalagriculture:supremium_shovel',
    'mysticalagriculture:supremium_sickle', 'mysticalagriculture:supremium_sword', 'mysticalagriculture:tertium_axe',
    'mysticalagriculture:tertium_boots', 'mysticalagriculture:tertium_bow', 'mysticalagriculture:tertium_chestplate',
    'mysticalagriculture:tertium_crossbow', 'mysticalagriculture:tertium_fishing_rod',
    'mysticalagriculture:tertium_helmet', 'mysticalagriculture:tertium_hoe', 'mysticalagriculture:tertium_leggings',
    'mysticalagriculture:tertium_pickaxe', 'mysticalagriculture:tertium_scythe', 'mysticalagriculture:tertium_shears',
    'mysticalagriculture:tertium_shovel', 'mysticalagriculture:tertium_sickle', 'mysticalagriculture:tertium_sword',
    'mysticalagriculture:tilling_aoe_i_augment', 'mysticalagriculture:tilling_aoe_ii_augment',
    'mysticalagriculture:tilling_aoe_iii_augment', 'mysticalagriculture:tilling_aoe_iv_augment',
    'mysticalagriculture:unattuned_augment', 'mysticalagriculture:water_breathing_augment',
    'mysticalagriculture:weakness_resistance_augment', 'mysticalagriculture:wither_resistance_augment',
    // Mystical Agriculture soulium daggers (the dagger eats a golden sword, the tiers eat the dagger)
    'mysticalagriculture:creative_soulium_dagger', 'mysticalagriculture:hostile_soulium_dagger', 'mysticalagriculture:passive_soulium_dagger', 'mysticalagriculture:soulium_dagger'
  ]
}
// Only plain data goes into `global`: functions created in the startup context are not reliably callable
// from server or client scripts, so each script defines its own helpers.
